# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            wcysai
tagline:          'A Jekyll theme'
description:      An undergraduate from Nanjing University, Department of Computer Science and Technology
url:              http://wcysai.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:              https://github.com/wcysai
