# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
description:      An undergraduate from Nanjing University, Department of Computer Science and Technology
email: wcysai@foxmail.com
url:              http://wcysai.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:              https://github.com/wcysai
